/**
 * Shared content type constants to ensure consistency across API, SDK, and storage.
 * These values must match exactly what is generated by metadata extraction.
 */
export const CONTENT_TYPES = [
  "readme",
  "api_documentation", // Note: matches metadata extraction output
  "tutorial",
  "configuration",
  "code",
  "other",
  "general", // fallback type from metadata extraction
] as const;

export type ContentType = (typeof CONTENT_TYPES)[number];

/**
 * Legacy API-facing content types with normalized values.
 * Used for backward compatibility with existing API clients.
 */
export const API_CONTENT_TYPES = [
  "readme",
  "api-docs", // API-facing name for api_documentation
  "tutorial",
  "configuration",
  "code",
  "other",
] as const;

export type ApiContentType = (typeof API_CONTENT_TYPES)[number];

/**
 * Maps API content type names to internal metadata content types
 */
export const API_TO_INTERNAL_CONTENT_TYPE: Record<ApiContentType, ContentType> =
  {
    readme: "readme",
    "api-docs": "api_documentation",
    tutorial: "tutorial",
    configuration: "configuration",
    code: "code",
    other: "other",
  };

/**
 * Maps internal content types to API-facing names
 */
export const INTERNAL_TO_API_CONTENT_TYPE: Record<
  ContentType,
  ApiContentType | undefined
> = {
  readme: "readme",
  api_documentation: "api-docs",
  tutorial: "tutorial",
  configuration: "configuration",
  code: "code",
  other: "other",
  general: "other", // map general to other for API
};
