[package]
name = "pdf-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.0"
lopdf = "0.36.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
