apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: api
        image: ghcr.io/winkk-dev/firecrawl:latest
        imagePullPolicy: Always
        args:  [ "pnpm", "run", "start:production" ]
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: firecrawl-config
        #- secretRef:
        #    name: firecrawl-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
