apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: worker
        image: ghcr.io/winkk-dev/firecrawl:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: firecrawl-config
        #- secretRef:
        #    name: firecrawl-secret
      - livenessProbe:
          httpGet:
            path: /v0/health/liveness
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        name: worker-container
      - readinessProbe:
          httpGet:
            path: /v0/health/readiness
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        name: worker-container